const mongoose = require('mongoose');
const mongooseDelete = require('mongoose-delete');
const { DeviceTypes } = require('../enums');
const Schema = mongoose.Schema;

const UserPushTokenSchema = new mongoose.Schema(
  {
    userId: { type: Schema.Types.ObjectId, ref: 'User' }, // User Id from the User Collection
    deviceType: { type: String, enum: Object.values(DeviceTypes) }, // User's device type either android, ios or web
    deviceId: String, // Device Id
    pushToken: String // Push Token generated by the FCM
  },
  {
    versionKey: false,
    timestamps: true
  }
);

UserPushTokenSchema.plugin(mongooseDelete, { overrideMethods: true });
module.exports = mongoose.model('UserPushToken', UserPushTokenSchema);
